apiVersion: aws.vault.upbound.io/v1alpha1
kind: AuthBackendClient
metadata:
  annotations:
    meta.upbound.io/example-id: aws/v1alpha1/authbackendclient
  labels:
    testing.upbound.io/example-name: example
  name: authbackendclient-accesskey/secretkey
spec:
  forProvider:
    accessKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    backend: cert
    secretKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
